steps;
- name: Call Function
  uses: argentumcode/actions-invoke-google-cloud-functions@master
  with:
    service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    url: https://us-central1-tpcg-chatbot-dev.cloudfunctions.net/github-actions-test
    payload: |
      {"env": "prd"}
    content_type: "application/json"
