name: Call Cloud Run Functions

on:
  push:
    branches:
      - master

steps;
- name: Call Function
  uses: SeongJung-Kim/datacollector@master
  with:
    service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    url: https://us-central1-tpcg-chatbot-dev.cloudfunctions.net/github-actions-test
    payload: |
      {"env": "prd"}
    content_type: "application/json"
